server:
  port: 80
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authenticator_db?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    locations: mysql
    enabled: true
    baseline-on-migrate: true
springdoc:
  pathsToMatch:
    - /auth/**
  swagger-ui:
    use-root-path: true